
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-6pm-4
owner: ucsb-cs156-w24
repo_name: team02-w24-6pm-4
pull_requests: [{"author":{"id":"U_kgDOBYEHjQ","is_bot":false,"login":"golo230","name":"Derek"},"headRefName":"DD-README","number":53,"title":"Update README.md","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-4/pull/53"},{"author":{"id":"U_kgDOBtxmKA","is_bot":false,"login":"Aavash-Adhikari","name":""},"headRefName":"AA-Articles-Controller","number":52,"title":"Finished Articles Controller and Tests","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-4/pull/52"}]
