
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-6pm-4
owner: ucsb-cs156-w24
repo_name: team02-w24-6pm-4
pull_requests: [{"author":{"id":"U_kgDOBdPPow","is_bot":false,"login":"ryanvo504","name":""},"headRefName":"rv-help","number":50,"title":"Finish help request","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-4/pull/50"},{"author":{"id":"MDQ6VXNlcjM4OTAxMzc1","is_bot":false,"login":"luxiangzh","name":"Luxiang Zhang"},"headRefName":"LZ-MenuItemReview-Controller","number":48,"title":"Complete MenuItemReviewController: add GET (index), POST (create), GET (show), PUT (edit) and DELETE endpoints","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-4/pull/48"},{"author":{"id":"U_kgDOBYEHjQ","is_bot":false,"login":"golo230","name":"Derek"},"headRefName":"DD-Recommendation-Request-Table","number":45,"title":"Dd recommendation request","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-4/pull/45"}]
